// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcKFp6eOltSftM_NNooEAovTuM5eb-Bt0',
    appId: '1:638688347032:web:b14204e846a4d52fbe21ed',
    messagingSenderId: '638688347032',
    projectId: 'eczema-f4f3c',
    authDomain: 'eczema-f4f3c.firebaseapp.com',
    storageBucket: 'eczema-f4f3c.firebasestorage.app',
    measurementId: 'G-D09783T222',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWekxpnZfvrNto02xdD4F-OKKXzq8NtM',
    appId: '1:638688347032:android:d25b84f50ed43e91be21ed',
    messagingSenderId: '638688347032',
    projectId: 'eczema-f4f3c',
    storageBucket: 'eczema-f4f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe9vlTh3GDnVpB8abWc9KYEhoD9-pqkCY',
    appId: '1:638688347032:ios:579550b91e8c9127be21ed',
    messagingSenderId: '638688347032',
    projectId: 'eczema-f4f3c',
    storageBucket: 'eczema-f4f3c.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

}